=== poohcid/class/webtech/lab5/4/employee.dtd
<!DOCTYPE company[
<!ELEMENT company (employee)>
<!ELEMENT employee (title, lastname, fistname, jobtitle, address)>
<!ELEMENT id (#PCDATA) >
<!ELEMENT title (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT fistname (#PCDATA)>
<!ELEMENT jobtitle (#PCDATA)>
<!ELEMENT address (#PCDATA)>
]>

=== poohcid/class/webtech/lab5/4/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "employee.dtd">
<company>
    <employee id="1">
        <id>1</id>
        <title lang="en">Ms.</title>
        <lastname>Davolio</lastname>
        <fistname>Nancy</fistname>
        <jobtitle>Sales Representative</jobtitle>
        <address>507 - 20th Ave. E. Apt. 2A</address>
    </employee>

    <employee id="2">
        <id>2</id>
        <title lang="en">Mr.</title>
        <lastname>Fuller</lastname>
        <fistname>Andrew</fistname>
        <jobtitle>Vice President, Sales</jobtitle>
        <address>908 W. Capital Way</address>
    </employee>

    <employee id="3">
        <id>3</id>
        <title lang="en">Ms.</title>
        <lastname>Leverling</lastname>
        <fistname>Janet</fistname>
        <jobtitle>Sales Representative</jobtitle>
        <address>722 Moss Bay Blvd.</address>
    </employee>

    <employee id="4">
        <id>4</id>
        <title lang="en">Mrs.</title>
        <lastname>Peacock</lastname>
        <fistname>Margaret</fistname>
        <jobtitle>Sales Representative</jobtitle>
        <address>4110 Old Redmond Rd.</address>
    </employee>

    <employee id="5">
        <id>5</id>
        <title lang="en">Mr.</title>
        <lastname>Buchanan</lastname>
        <fistname>Steven</fistname>
        <jobtitle>Sales Manager</jobtitle>
        <address>14 Garrett Hill</address>
    </employee>

    <employee id="6">
        <id>6</id>
        <title lang="en">Mr.</title>
        <lastname>Suyama</lastname>
        <fistname>Michael</fistname>
        <jobtitle>Sales Representative</jobtitle>
        <address>Coventry House Miner Rd.</address>
    </employee>

    <employee id="7">
        <id>7</id>
        <title lang="en">Mr.</title>
        <lastname>King</lastname>
        <fistname>Robert</fistname>
        <jobtitle>Sales Representative</jobtitle>
        <address>Edgeham Hollow Winchester Way</address>
    </employee>

    <employee id="8">
        <id>8</id>
        <title lang="en">Ms.</title>
        <lastname>Callahan</lastname>
        <fistname>Laura</fistname>
        <jobtitle>Inside Sales Coordinator</jobtitle>
        <address>4726 - 11th Ave. N.E.</address>
    </employee>

    <employee id="9">
        <id>9</id>
        <title lang="en">Ms.</title>
        <lastname>Dodsworth</lastname>
        <fistname>Anne</fistname>
        <jobtitle>Sales Representative</jobtitle>
        <address>7 Houndstooth Rd.</address>
    </employee>
</company>
